In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
tf.__version__

'2.17.0'

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a.ndim



1

In [6]:
sport = tf.constant('Tennis', tf.string)
number = tf.constant(1.12)
print(sport)
print(number)
print("sport is a {}-d Tensor".format(tf.rank(sport).numpy()))
print(" Number is a {}-d Tensor".format(tf.rank(number).numpy()))

tf.Tensor(b'Tennis', shape=(), dtype=string)
tf.Tensor(1.12, shape=(), dtype=float32)
sport is a 0-d Tensor
 Number is a 0-d Tensor


In [7]:
tf.rank(sport).numpy()

0

One Dimnesional Tensor

In [8]:
sports=tf.constant(['Tennis','Basketball'], tf.string)
numbers=tf.constant([1.1,1.2,1.3], tf.float64)

print(' sports is a {}-d Tensor with shape {}'.format(tf.rank(sports).numpy(),tf.shape(sports)))
print('numbers is a {}-d Tensor with shape {}'.format(tf.rank(numbers).numpy(),tf.shape(numbers)))

 sports is a 1-d Tensor with shape [2]
numbers is a 1-d Tensor with shape [3]


In [9]:
tf.shape(sports).numpy()

array([2], dtype=int32)

In [10]:
matrix = tf.constant([[1,2,4],[1,4,5]])

assert isinstance(matrix, tf.Tensor)
assert tf.rank(matrix).numpy()==2

In [11]:
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [1, 4, 5]], dtype=int32)>

In [12]:
tf.rank(matrix).numpy(), tf.shape(matrix).numpy()

(2, array([2, 3], dtype=int32))

In [13]:
images = tf.zeros(shape=(3,3,3,2))
images




<tf.Tensor: shape=(3, 3, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [14]:
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [1, 4, 5]], dtype=int32)>

In [15]:
row_vector = matrix[1]
print(' Row Vector :{}'.format(row_vector.numpy()))

 Row Vector :[1 4 5]


In [16]:
col_vector = matrix[:,1]
print('Column Vector : {}'.format(col_vector.numpy()))

Column Vector : [2 4]


In [17]:
scaler = matrix[1,2]
print(' Scaler:{}'.format(scaler.numpy()))

 Scaler:5


In [25]:
a=tf.constant([15,34])
b= tf.constant(61)

c1 = tf.add(a,b)
c2 = a+b
print(c1)
print(c2)
print(c1.numpy().tolist())

tf.Tensor([76 95], shape=(2,), dtype=int32)
tf.Tensor([76 95], shape=(2,), dtype=int32)
[76, 95]
